# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import pytest
import allo
from allo.ir.types import int32, float32
import numpy as np


def test_example_backend_basic():
    """Test the example extensible backend with a simple kernel."""

    def vadd(A: int32[32], B: int32[32]) -> int32[32]:
        C: int32[32] = 0
        for i in allo.grid(32, name="C"):
            C[i] = A[i] + B[i]
        return C

    s = allo.customize(vadd)
    mod = s.build(target="byoc")

    # Check that we got an ExampleModule
    assert mod.__class__.__name__ == "ExampleModule"
    assert mod.top_func_name == "vadd"
    print(f"Module: {mod}")

    # Test get_ir method
    ir = mod.get_ir()
    assert "vadd" in ir
    assert "func" in ir.lower()
    print("IR generated successfully")

    # Test codegen method
    code = mod.codegen()
    assert "Generated by ExampleModule" in code
    assert "vadd" in code
    print("Codegen successful")
    print("Passed!")


def test_example_backend_with_options():
    """Test the example backend with various build options."""

    def gemm(A: int32[16, 16], B: int32[16, 16]) -> int32[16, 16]:
        C: int32[16, 16] = 0
        for i, j, k in allo.grid(16, 16, 16, name="C"):
            C[i, j] += A[i, k] * B[k, j]
        return C

    s = allo.customize(gemm)
    mod = s.build(
        target="byoc",
        mode="custom_mode",
        project="my_project",
        configs={"option1": True, "option2": 42},
    )

    assert mod.mode == "custom_mode"
    assert mod.project == "my_project"
    assert mod.configs == {"option1": True, "option2": 42}
    print(f"Module with options: {mod}")
    print("Passed!")


def test_example_backend_run_not_implemented():
    """Test that the run method raises NotImplementedError."""

    def add_one(A: int32[8]) -> int32[8]:
        B: int32[8] = 0
        for i in allo.grid(8):
            B[i] = A[i] + 1
        return B

    s = allo.customize(add_one)
    mod = s.build(target="byoc")

    with pytest.raises(NotImplementedError):
        mod()
    print("Passed!")


def test_invalid_backend():
    """Test that an invalid backend raises NotImplementedError."""

    def simple(A: int32[4]) -> int32[4]:
        B: int32[4] = 0
        for i in allo.grid(4):
            B[i] = A[i]
        return B

    s = allo.customize(simple)

    with pytest.raises(NotImplementedError) as excinfo:
        s.build(target="nonexistent_backend_xyz")

    assert "nonexistent_backend_xyz" in str(excinfo.value)
    assert "not supported" in str(excinfo.value)
    print("Passed!")


if __name__ == "__main__":
    test_example_backend_basic()
    test_example_backend_with_options()
    test_example_backend_run_not_implemented()
    test_invalid_backend()
