version: 2.1

jobs:
  build:
    docker:
      - image: chhzh123/allo:latest
    steps:
      - checkout
      - run:
          name: Install Git in Container
          command: |
            sudo apt-get update && sudo apt-get -y install git
            # Set the current working directory as safe
            git config --global --add safe.directory $PWD
      - run:
          name: Build Allo
          shell: bash
          command: |
            source activate allo
            export LLVM_BUILD_DIR=/root/llvm-project/build
            python3 -m pip install https://github.com/cornell-zhang/past-python-bindings/releases/download/65f989b/past-0.7.2-cp312-cp312-linux_x86_64.whl
            NUM_THREADS=2 python3 -m pip install -v -e .
      - run:
          name: Formatting Check
          shell: bash
          command: |
            source activate allo
            bash scripts/lint/task_lint.sh
      - run:
          name: Run Tests
          shell: bash
          command: |
            source activate allo
            export PATH=/root/llvm-project/build/bin:${PATH}
            python3 -m pytest tests -v
            python3 -m pytest tutorials -v
            python3 -m pytest examples/polybench -v

workflows:
  build_and_test:
    jobs:
      - build