# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    working_directory: ~/allo
    docker:
      - image: chhzh123/allo:llvm-19.x-py3.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: large
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Build Allo
          command: |
            source activate allo
            python3 -m pip install -v -e .
      - run:
          name: Formatting Check
          command: |
            source activate allo
            bash ./.circleci/task_lint.sh
      - run: 
          name: Allo Tests
          command: |
            source activate allo
            python3 -m pytest tests -v
            python3 -m pytest tutorials -v
            python3 -m pytest examples/polybench -v
